class Genetic :
    Goal = ""
    Alphabet = ""
    PercentCrossover = 0
    PercentMutation = 0
    MaxMutation = 0
    MaxPopulation = 0
    IsFound = False
    Elitism = True
    NumberSelection = 5
    CrossoverPoints = 2
    Population = None
    MaxGenerations = 0